id: AF7C55404
title: Toh_271-The_Eight_Buddhas-v2
type: translation
pechas:
- IAA20E4FA
- I27371D02
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-068-005
  eft-text-version: 1.1.5 2020
  title: Toh_271-The_Eight_Buddhas-v2
alignment_to_base:
  IAA20E4FA/1038: '6673'
  I27371D02/E17D: '6673'
